version: '3.8'

services:
  app:
    build: .
    ports:
      - '3005:3005'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    command: npm start
db:
image: postgres:13
restart: always
environment:
